"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { RewardFormSheet } from "@/components/owner/reward-form-sheet";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Icons, IconSize } from "@/components/ui/icons";
import { SectionHeader } from "@/components/ui/section-header";
import { SegmentedControl } from "@/components/ui/segmented-control";
import { Field } from "@/components/ui/field";
import {
  setRewardActive,
  setRewardArchived,
  upsertLoyaltyProgram,
} from "@/lib/api/owner-back-office";
import { ownerErrorMessage } from "@/lib/api/owner-errors";
import { earnSentence, rewardValueLabel } from "@/lib/analytics";
import { createClient } from "@/lib/supabase/client";
import type {
  LoyaltyEarnMode,
  LoyaltyProgram,
  LoyaltyReward,
} from "@/lib/types/back-office";

/**
 * The loyalty program and its reward menu — a port of
 * `tho/app/lib/business/loyalty/loyalty_settings_screen.dart`.
 *
 * ## Two numbers, one of which is live
 *
 * `earn_mode` decides which figure is used and which is ignored, so only one input is on screen
 * at a time and the preview sentence below it is generated by `earnSentence` — the same function
 * the customer's own loyalty card will use in 2f, so an owner reading "1 point per Nu 50 spent"
 * here is reading exactly what a customer will be told.
 *
 * `pointsForBooking` in `lib/analytics.ts` mirrors the earn **trigger**, not this form, which is
 * what makes the preview a claim about the database rather than about the UI.
 *
 * ## Removing a reward restores its previous state, not "on"
 *
 * A reward that was paused when it was archived comes back paused. Restoring it to active would
 * quietly publish something the owner had deliberately switched off — which is why
 * `setRewardArchived` takes the previous `isActive` rather than assuming.
 *
 * ## The Growth gate here is client-side only
 *
 * `loyalty_programs_write_owner` checks ownership and stops, and `loyalty_programs_select_public`
 * publishes **any** active program regardless of plan. So a Basic salon can switch loyalty on
 * today and customers will see it; loyalty is a Growth entitlement in `entitlements.ts`, the page
 * gates on it, and that gate is the only one in existence. Reported upstream.
 */
export function LoyaltyForm({
  businessId,
  program,
  rewards,
  pendingRedemptions,
}: {
  businessId: string;
  program: LoyaltyProgram | null;
  rewards: LoyaltyReward[];
  pendingRedemptions: number;
}) {
  const router = useRouter();
  const [isActive, setIsActive] = useState(program?.isActive ?? false);
  const [earnMode, setEarnMode] = useState<LoyaltyEarnMode>(program?.earnMode ?? "per_visit");
  const [pointsPerVisit, setPointsPerVisit] = useState(String(program?.pointsPerVisit ?? 10));
  const [nuPerPoint, setNuPerPoint] = useState(String(program?.nuPerPoint ?? 10));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState<LoyaltyReward | "new" | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);

  const ppv = Number.parseInt(pointsPerVisit.trim(), 10);
  const npp = Number.parseInt(nuPerPoint.trim(), 10);
  const preview = earnSentence({
    businessId,
    isActive,
    earnMode,
    pointsPerVisit: Number.isFinite(ppv) ? ppv : 10,
    nuPerPoint: Number.isFinite(npp) ? npp : 10,
  });

  async function save() {
    setError(null);
    // The two CHECKs: `points_per_visit >= 0` and `nu_per_point > 0`. Zero points per visit is
    // legal and means "earning is off but the program exists", which is a real state.
    if (earnMode === "per_visit" && (!Number.isFinite(ppv) || ppv < 0)) {
      setError("Points per visit can't be negative.");
      return;
    }
    if (earnMode === "per_spend" && (!Number.isFinite(npp) || npp <= 0)) {
      setError("Nu per point has to be at least 1.");
      return;
    }
    setSaving(true);
    try {
      await upsertLoyaltyProgram(createClient(), businessId, {
        isActive,
        earnMode,
        pointsPerVisit: Number.isFinite(ppv) ? ppv : 10,
        nuPerPoint: Number.isFinite(npp) ? npp : 10,
      });
      toast.success("Loyalty settings saved.");
      router.refresh();
    } catch (caught) {
      setError(ownerErrorMessage("saveLoyaltyProgram", caught));
    } finally {
      setSaving(false);
    }
  }

  async function toggleReward(reward: LoyaltyReward) {
    setBusyId(reward.id);
    try {
      await setRewardActive(createClient(), reward.id, !reward.isActive);
      router.refresh();
    } catch (caught) {
      toast.error(ownerErrorMessage("toggleReward", caught));
    } finally {
      setBusyId(null);
    }
  }

  async function archiveReward(reward: LoyaltyReward) {
    setBusyId(reward.id);
    try {
      await setRewardArchived(createClient(), reward.id, true);
      router.refresh();
      toast.success("Reward removed.", {
        action: {
          label: "Undo",
          onClick: () => {
            void (async () => {
              try {
                // Back to the state it was in, not to active — see the module comment.
                await setRewardArchived(createClient(), reward.id, false, reward.isActive);
                router.refresh();
              } catch (caught) {
                toast.error(ownerErrorMessage("archiveReward", caught));
              }
            })();
          },
        },
      });
    } catch (caught) {
      toast.error(ownerErrorMessage("archiveReward", caught));
    } finally {
      setBusyId(null);
    }
  }

  return (
    <div className="px-base py-lg mx-auto w-full max-w-[720px] tablet:px-lg">
      <SectionHeader title="Loyalty" as="h1" />
      <p className="text-body-sm text-muted mb-lg">
        Points for coming back, redeemed at the counter for something you choose.
      </p>

      <Link
        href="/business/loyalty/redemptions"
        className="border-hairline-soft p-base gap-md hover:bg-surface-soft mb-lg flex items-center rounded-md border"
      >
        <span className="bg-surface-soft text-ink grid size-11 shrink-0 place-items-center rounded-sm">
          <Icons.inbox style={{ width: IconSize.sm, height: IconSize.sm }} aria-hidden />
        </span>
        <span className="min-w-0 flex-1">
          <span className="text-title text-ink block font-medium">Redemptions</span>
          <span className="text-body-sm text-muted block">
            {pendingRedemptions === 0
              ? "Nothing waiting to be honoured"
              : `${pendingRedemptions} waiting to be honoured`}
          </span>
        </span>
        <Icons.chevronRight
          className="text-muted-soft shrink-0"
          style={{ width: IconSize.sm, height: IconSize.sm }}
          aria-hidden
        />
      </Link>

      <label className="border-hairline-soft p-base gap-md mb-lg flex cursor-pointer items-center rounded-md border">
        <span className="min-w-0 flex-1">
          <span className="text-title text-ink block font-medium">Loyalty program</span>
          <span className="text-body-sm text-muted block">
            {isActive ? "On — customers earn on every completed visit" : "Off"}
          </span>
        </span>
        <input
          type="checkbox"
          checked={isActive}
          onChange={(e) => setIsActive(e.target.checked)}
          className="accent-rausch-cta size-5 shrink-0"
        />
      </label>

      <SectionHeader title="How points are earned" />
      <div className="mb-md">
        <SegmentedControl
          label="How points are earned"
          labels={["Per visit", "Per spend"]}
          index={earnMode === "per_visit" ? 0 : 1}
          onChange={(i) => setEarnMode(i === 0 ? "per_visit" : "per_spend")}
        />
      </div>

      {earnMode === "per_visit" ? (
        <Field
          label="Points per visit"
          value={pointsPerVisit}
          onChange={setPointsPerVisit}
          type="number"
          inputMode="numeric"
          min={0}
        />
      ) : (
        <Field
          label="Nu spent per 1 point"
          value={nuPerPoint}
          onChange={setNuPerPoint}
          type="number"
          inputMode="numeric"
          min={1}
        />
      )}
      <p className="text-body-sm text-muted mt-sm">{preview}</p>

      {error ? <p className="text-body-sm text-error-text mt-sm">{error}</p> : null}

      <div className="mt-base mb-lg">
        <Button busy={saving} onClick={() => void save()}>
          Save program
        </Button>
      </div>

      <div className="mb-sm flex items-center justify-between">
        <SectionHeader title="Rewards" />
        <Button variant="quiet" onClick={() => setEditing("new")}>
          <Icons.add style={{ width: IconSize.xs, height: IconSize.xs }} aria-hidden />
          Add reward
        </Button>
      </div>

      {rewards.length === 0 ? (
        <EmptyState
          icon={Icons.gift}
          title="No rewards yet"
          message="Add something customers can redeem points for."
        />
      ) : (
        <ul className="gap-md flex flex-col">
          {rewards.map((r) => (
            <li
              key={r.id}
              className="border-hairline-soft p-md gap-sm flex items-center rounded-md border"
            >
              <span className="min-w-0 flex-1">
                <span className="text-title text-ink block truncate font-medium">{r.name}</span>
                <span className="text-body-sm text-muted block">
                  {rewardValueLabel(r)} · {r.pointCost} pts
                </span>
              </span>
              <Button
                variant="quiet"
                onClick={() => setEditing(r)}
                aria-label={`Edit ${r.name}`}
                className="px-sm shrink-0"
              >
                <Icons.edit style={{ width: IconSize.sm, height: IconSize.sm }} aria-hidden />
              </Button>
              <Button
                variant="quiet"
                onClick={() => void archiveReward(r)}
                aria-label={`Remove ${r.name}`}
                className="px-sm shrink-0"
              >
                <Icons.trash style={{ width: IconSize.sm, height: IconSize.sm }} aria-hidden />
              </Button>
              <label className="flex shrink-0 cursor-pointer items-center">
                <span className="sr-only">
                  {r.isActive ? `Pause ${r.name}` : `Offer ${r.name} again`}
                </span>
                <input
                  type="checkbox"
                  checked={r.isActive}
                  disabled={busyId === r.id}
                  onChange={() => void toggleReward(r)}
                  className="accent-rausch-cta size-5"
                />
              </label>
            </li>
          ))}
        </ul>
      )}

      {editing !== null ? (
        <RewardFormSheet
          key={editing === "new" ? "new" : editing.id}
          businessId={businessId}
          reward={editing === "new" ? null : editing}
          onClose={() => setEditing(null)}
        />
      ) : null}
    </div>
  );
}
