/**
 * Keyword-bearing URLs for the two routes that name a real-world thing.
 *
 * `/salon/<uuid>` and `/stylist/<uuid>` are the most-linked pages this app has and the
 * only ones a search engine could ever rank for a salon's own name — and until now the
 * URL carried none of it. `/salon/0b000000-0000-4000-8000-000000000001` tells a crawler,
 * and a person deciding whether to click a result, precisely nothing.
 *
 * ## The trailing id is the lookup key, and that is the whole design
 *
 * There is **no `slug` column**, and there cannot be one from here: the schema lives in
 * `../tho/supabase/migrations/` and this repo never writes SQL. So the slug is *derived*
 * — minted from the name at render time and parsed back to the id at request time — and
 * the id is what the database is asked for. Three things follow, and they are the reason
 * this shape was chosen over a real slug column:
 *
 * - **A rename cannot 404.** `Norzin Salon & Spa` becoming `Norzin Studio` changes the
 *   minted slug, but the old URL still carries the same trailing id, so it still resolves
 *   — and the canonical on the page points at the new form, which is how a crawler learns
 *   about the move. A slug column without a redirect table would break every existing
 *   link on a rename.
 * - **Two salons may share a name.** The id disambiguates them for free. A `unique(slug)`
 *   column would have to reject or suffix the second one.
 * - **Nothing else has to change.** `sitemap.ts`, every `<Link>`, and the QR contract are
 *   the only callers, and `/q/<businessId>` is deliberately *not* one of them — its shape
 *   is fixed by `QueueDeepLink.businessIdFrom` in `../tho`, which parses a bare id out of
 *   a printed poster. Slugging it would break every QR already on a counter.
 *
 * ## A UUID is not the only id shape here, and that is why the pattern is anchored
 *
 * The seed ids are UUIDs (`0b000000-…`) but so is the *tail of every slug*, so a greedy
 * match would be ambiguous. `UUID_TAIL` is anchored to the end of the string and the
 * separator before it is required, which makes `parseEntityId` total: a bare id, a
 * slugged id, or nothing.
 */

/** A v4-shaped id at the very end of a path segment, with its separating hyphen. */
const UUID_TAIL =
  /-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i;

/** The same shape, as the entire segment. */
const BARE_UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * A name, reduced to URL-safe words.
 *
 * **`NFKD` before stripping marks, not after**, because a salon's name is owner-typed and
 * routinely carries diacritics — decomposing first turns `é` into `e` + a combining mark,
 * so removing the mark leaves a letter rather than dropping the character entirely.
 * Non-Latin scripts (the live data has Dzongkha and Arabic examples) reduce to nothing,
 * which is why `salonPath` tolerates an empty slug and falls back to the bare id rather
 * than emitting a URL that begins with a stray hyphen.
 */
export function slugifyName(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/g, "");
}

/**
 * The canonical path for a salon, and the one every link and the sitemap must use.
 *
 * Falls back to the bare id when the name slugifies to nothing — a name written entirely
 * in a non-Latin script, which the live data has. `/salon/-<uuid>` would be the
 * alternative and it is worse than a plain id in every way.
 */
export function salonPath(business: { id: string; name?: string | null }): string {
  return entityPath("/salon", business.id, business.name);
}

/** The canonical path for a stylist. Same rules as `salonPath`. */
export function stylistPath(staff: { id: string; displayName?: string | null }): string {
  return entityPath("/stylist", staff.id, staff.displayName);
}

/**
 * **Minting and parsing are inverse, and the id guard is what makes that true.**
 *
 * `parseEntityId` recovers the id by finding a UUID at the end of the segment, so a slug
 * appended to an id of any *other* shape would produce a URL this app cannot read back —
 * a 404 on a page that exists, generated by its own link. Every id in this schema is a
 * UUID, so the guard never fires in production; it fires in tests and it would fire on
 * the day something upstream changed key type, which is exactly when a silent 404 would
 * be hardest to trace.
 */
function entityPath(prefix: string, id: string, name: string | null | undefined): string {
  if (!BARE_UUID.test(id)) return `${prefix}/${id}`;
  const slug = name ? slugifyName(name) : "";
  return slug ? `${prefix}/${slug}-${id}` : `${prefix}/${id}`;
}

/**
 * The id inside a route parameter, whether or not it carries a slug.
 *
 * Returns `null` for anything that is not one of the two shapes, which is what lets the
 * route answer `notFound()` without asking the database about a string that cannot be an
 * id. That matters more than it looks: without it every crawl of a mistyped URL costs a
 * round trip.
 */
export function parseEntityId(param: string): string | null {
  const decoded = safeDecode(param);
  if (BARE_UUID.test(decoded)) return decoded.toLowerCase();
  const tail = UUID_TAIL.exec(decoded);
  return tail ? tail[1].toLowerCase() : null;
}

/**
 * Whether the visitor already arrived at the canonical form.
 *
 * The route compares this against the minted path and issues a permanent redirect when it
 * differs, so a bare id, an out-of-date slug and a hand-typed variation all converge on
 * one URL — which is what stops three URLs competing for one salon. **Case matters here
 * and is normalised**, because a UUID is hex and both cases resolve.
 */
export function isCanonicalParam(param: string, canonicalPath: string): boolean {
  const expected = canonicalPath.slice(canonicalPath.lastIndexOf("/") + 1);
  return safeDecode(param).toLowerCase() === expected.toLowerCase();
}

/** `decodeURIComponent` throws on a malformed escape; a bad URL is not an exception. */
function safeDecode(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}
